export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_GRAPH = 'LOAD_GRAPH';
export const LOAD_RETAILERS = 'LOAD_RETAILERS';
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const RECIEVE_PRODUCT = "RECIEVE_PRODUCT";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
