export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';
export const LOAD_GRAPH = 'LOAD_GRAPH';
export const LOAD_RETAILERS = 'LOAD_RETAILERS';
/*
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
*/
